POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "google",
    "author": "larry & sergey",
    "url": "https://www.google.com/",
    "likes": 7
}

###
GET http://localhost:3003/api/blogs