GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Youtube",
    "author": "GOOGLE",
    "url": "https://www.youtube.com/",
    "likes": 9
}