GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "ReactJS",
    "author": "Meta",
    "url": "https://react.dev/",
    "likes": 3
}