DELETE http://localhost:3001/api/notes/3

###
GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/645ff62abbd0c0825cb994bb

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "new note",
    "important": true
}

###
PUT http://localhost:3001/api/notes/6488df057827a8bf9af2c3ef
Content-Type: application/json

{
    "content": "new note",
    "important": true
}